created bill view page
LilyCatFiddy/receipt-splitter pull request #16
Opened 2023-03-27 23:55 UTC by Shibainuinuinu

2023-03-28 01:08 UTC, Cosze commented on pages/billViewPage.js
> +    )
Please refactor to use the new layout component from [this PR](https://github.com/LilyCatFiddy/receipt-splitter/pull/17) after it gets merged so we have a consistent layout

2023-04-04 18:18 UTC, kathyye15 approved these changes

2023-04-10 18:43 UTC, Cosze commented on assets/main.css
> +    border-radius: 0.5em;
For ease of use please reorient CSS properties in alphabetical order

2023-04-10 18:47 UTC, Cosze requested changes

2023-04-10 18:47 UTC, Cosze commented on assets/main.css
> +    border-radius: 0.5em;
I highlighted this but check all of the new styles you've added

2023-04-12 01:10 UTC, Cosze approved these changes

2023-04-12 01:10 UTC, merged